# Generated by Django 6.0.5 on 2026-06-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=56)),
                ('employee_email', models.EmailField(max_length=56)),
                ('employee_phone', models.CharField(max_length=56)),
                ('employee_address', models.CharField(max_length=56)),
                ('employee_salary', models.FloatField()),
                ('about', models.TextField()),
                ('Position', models.CharField(choices=[('Manager', 'Manager'), ('Software Engineer', 'Software Engineer'), ('HR', 'HR'), ('Other', 'Other')], max_length=56)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
