# Generated by Django 6.0.5 on 2026-05-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=56)),
                ('company_location', models.CharField(max_length=56)),
                ('company_email', models.EmailField(max_length=56)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=56)),
            ],
        ),
    ]
