# Generated by Django 6.0.5 on 2026-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Position',
            new_name='position',
        ),
    ]
