# Generated by Django 6.0.5 on 2026-06-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_position_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address',
            field=models.CharField(max_length=100),
        ),
    ]
